INSERT INTO `data_module_enum` VALUES ('5', '39', '高度', 'GD', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('6', '39', '吊顶材料', 'DDCL', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('7', '39', '辅助', 'FZ', '3', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('8', '40', '地面材料', 'DMCL', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('9', '40', '防潮药水', 'FCYS', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('10', '31', '墙面材料', 'QMCL', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('11', '31', '踢脚材料', 'TJCL', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('12', '31', '踢脚高度', 'TJGD', '3', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('13', '32', '门', 'M', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('14', '32', '门开关', 'MKG', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('15', '32', '窗', 'C', '3', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('16', '34', '辐射当量', 'FSDL', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('17', '34', '防辐射材料', 'FFSCL', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('18', '35', '给水', 'GS', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('19', '35', '给水开关', 'GSKG', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('20', '36', '排水', 'PS', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('21', '37', '气体种类', 'QTZL', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('22', '37', '气体传输系统', 'QTCSXT', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('23', '38', '插座', 'CZ', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('24', '38', '灯光', 'DG', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('25', '21', '弱电信息', 'RDXX', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('26', '21', '物流', 'WL', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('27', '21', '通排风', 'TPF', '1', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('28', '21', '洁净等级', 'JJDJ', '2', null, null, null, null);
INSERT INTO `data_module_enum` VALUES ('29', '21', '空调', 'KT', '3', null, null, null, null);

INSERT INTO `data_module_enum_param` VALUES ('1', '40', '8', 'PVC块材', 'PVCKC', '1', null, null, null, null);
INSERT INTO `data_module_enum_param` VALUES ('2', '40', '8', 'PVC卷材', 'PVCJC', '2', null, null, null, null);
INSERT INTO `data_module_enum_param` VALUES ('3', '40', '8', '天然橡胶', 'TRXJ', '3', null, null, null, null);
INSERT INTO `data_module_enum_param` VALUES ('4', '40', '8', '瓷砖', 'CZ', '4', null, null, null, null);
INSERT INTO `data_module_enum_param` VALUES ('5', '40', '8', '地毯', 'DT', '5', null, null, null, null);
INSERT INTO `data_module_enum_param` VALUES ('6', '40', '8', '自留坪地面', 'ZLPDM', '6', null, null, null, null);
INSERT INTO `data_module_enum_param` VALUES ('7', '40', '8', '大理石', 'DLS', '7', null, null, null, null);

INSERT INTO `room_data_module` VALUES ('21', '弱电信息及物流系统', '1', 'RDXXJWLXT', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('22', '通风空调系统', '1', 'TFKTXT', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('31', '墙面及踢脚', '1', 'QMJTJ', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('32', '门窗', '1', 'MC', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('33', '五金', '1', 'WJ', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('34', '屏蔽', '1', 'PB', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('35', '给水', '1', 'GS', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('36', '排水', '1', 'PS', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('37', '医疗气体', '1', 'YLQT', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('38', '电气及照明', '1', 'DQJZM', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('39', '天花', '1', 'TH', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('40', '地面', '1', 'DM', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('41', '医疗设备及显示屏', '1', 'YLSBJXSP', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('42', '非医疗设备', '1', 'FYLSB', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('43', '固定家具', '1', 'GDJJ', null, null, null, null);
INSERT INTO `room_data_module` VALUES ('44', '活动家具', '1', 'HDJJ', null, null, null, null);
