CREATE TABLE data_module_enum (
  ID bigint(12) NOT NULL AUTO_INCREMENT COMMENT '序列编号',
  MODULE_ID bigint(12) NOT NULL COMMENT '模块编号',
  ENUM_NAME varchar(255) DEFAULT NULL COMMENT '枚举名称',
  ENUM_CODE varchar(255) DEFAULT NULL COMMENT '枚举简码',
  ORDER_IDX smallint(6) DEFAULT NULL COMMENT '顺序编号',
  NAME_SPELLING varchar(255) DEFAULT NULL COMMENT '名称拼音',
  NAME_CODE varchar(255) DEFAULT NULL COMMENT '名称简拼',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  NOTE varchar(255) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY (ID)
) AUTO_INCREMENT=30 DEFAULT CHARSET=utf8;

CREATE TABLE data_module_enum_param (
  ID bigint(12) NOT NULL AUTO_INCREMENT COMMENT '序列编号',
  MODULE_ID bigint(12) NOT NULL COMMENT '模块编号',
  ENUM_ID bigint(12) NOT NULL COMMENT '枚举编号',
  ENUM_PARAM_NAME varchar(255) DEFAULT NULL COMMENT '枚举参数名称',
  ENUM_PARAM_CODE varchar(255) DEFAULT NULL COMMENT '枚举参数简码',
  ORDER_IDX smallint(6) DEFAULT NULL COMMENT '顺序编号',
  NAME_SPELLING varchar(255) DEFAULT NULL COMMENT '名称拼音',
  NAME_CODE varchar(255) DEFAULT NULL COMMENT '名称简拼',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  NOTE varchar(255) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY (ID)
) AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

CREATE TABLE room_data_module (
  ID bigint(12) NOT NULL AUTO_INCREMENT COMMENT '序列编号',
  MODULE_NAME varchar(255) DEFAULT NULL COMMENT '模块名称',
  MODULE_TYPE varchar(8) DEFAULT NULL COMMENT '模块分类：1.装饰装修；2.设备；3.耗材；9.其它',
  MODULE_CODE varchar(255) DEFAULT NULL COMMENT '模块简码',
  NAME_SPELLING varchar(255) DEFAULT NULL COMMENT '名称拼音',
  NAME_CODE varchar(255) DEFAULT NULL COMMENT '名称简拼',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  NOTE varchar(255) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY (ID)
) AUTO_INCREMENT=45 DEFAULT CHARSET=utf8;
