package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.AreaSummary;
import com.chilicool.hdtools.domain.AreaSummaryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AreaSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int countByExample(AreaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int deleteByExample(AreaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int insert(AreaSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int insertSelective(AreaSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    List<AreaSummary> selectByExample(AreaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    AreaSummary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AreaSummary record, @Param("example") AreaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AreaSummary record, @Param("example") AreaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AreaSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AreaSummary record);
}