package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.DataModuleEnum;
import com.chilicool.hdtools.domain.DataModuleEnumExample;
import java.util.List;

import com.chilicool.hdtools.model.ModuleEnumSimp;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DataModuleEnumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int countByExample(DataModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int deleteByExample(DataModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int insert(DataModuleEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int insertSelective(DataModuleEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    List<DataModuleEnum> selectByExample(DataModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    DataModuleEnum selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DataModuleEnum record, @Param("example") DataModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DataModuleEnum record, @Param("example") DataModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataModuleEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_module_enum
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataModuleEnum record);

    List<ModuleEnumSimp> getModuleEnumWithModuleId(Long moduleId);
}