package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.DeptType;
import com.chilicool.hdtools.domain.DeptTypeExample;
import java.util.List;
import java.util.Map;

import com.chilicool.hdtools.model.PlanAreaModel;
import com.chilicool.hdtools.model.SumyInfoModel;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DeptTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int countByExample(DeptTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int deleteByExample(DeptTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int insert(DeptType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int insertSelective(DeptType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    List<DeptType> selectByExample(DeptTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    DeptType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeptType record, @Param("example") DeptTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeptType record, @Param("example") DeptTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeptType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeptType record);

    /**
     * 查询所有汇总信息
     *
     * @param projId
     * @return
     */
    List<SumyInfoModel> loadAllSumyInfo(Long projId);

    /**
     * 分级查询所有汇总信息
     *
     * @param inParam
     * @return
     */
    List<SumyInfoModel> loadAllSumyInfoWithLevel(Map<String, Object> inParam);

    /**
     * 获取所有部门分类的规划面积值
      * @param projId
     * @return
     */
    List<PlanAreaModel> loadAllDeptModel(Long projId);

    /**
     * 获取所有部门分类的设计面积值
     * @param projId
     * @return
     */
    List<PlanAreaModel> loadAllDeptDesignAreaModel(Long projId);
}