package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.DeptSummary;
import com.chilicool.hdtools.domain.DeptSummaryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DeptSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int countByExample(DeptSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int deleteByExample(DeptSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int insert(DeptSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int insertSelective(DeptSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    List<DeptSummary> selectByExample(DeptSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    DeptSummary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeptSummary record, @Param("example") DeptSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeptSummary record, @Param("example") DeptSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeptSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeptSummary record);
}