package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.ParamsView;
import com.chilicool.hdtools.domain.ParamsViewExample;
import com.chilicool.hdtools.domain.ParamsViewWithBLOBs;
import java.util.List;

import com.chilicool.hdtools.model.SpecRoomDataModel;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ParamsViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    int countByExample(ParamsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    int deleteByExample(ParamsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    int insert(ParamsViewWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    int insertSelective(ParamsViewWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    List<ParamsViewWithBLOBs> selectByExampleWithBLOBs(ParamsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    List<ParamsView> selectByExample(ParamsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ParamsViewWithBLOBs record, @Param("example") ParamsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ParamsViewWithBLOBs record, @Param("example") ParamsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table params_view
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ParamsView record, @Param("example") ParamsViewExample example);

    /**
     * 查询所有房间参数
     *
     * @param example
     * @return
     */
    public List<SpecRoomDataModel> loadAllSpecRoomData(ParamsViewExample example);
}