package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.ProjBaseInfo;
import com.chilicool.hdtools.domain.ProjBaseInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProjBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int countByExample(ProjBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int deleteByExample(ProjBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int insert(ProjBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int insertSelective(ProjBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    List<ProjBaseInfo> selectByExample(ProjBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    ProjBaseInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjBaseInfo record, @Param("example") ProjBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjBaseInfo record, @Param("example") ProjBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_base_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjBaseInfo record);
}