package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.ProjVersion;
import com.chilicool.hdtools.domain.ProjVersionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProjVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    int countByExample(ProjVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    int deleteByExample(ProjVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    int insert(ProjVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    int insertSelective(ProjVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    List<ProjVersion> selectByExample(ProjVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjVersion record, @Param("example") ProjVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjVersion record, @Param("example") ProjVersionExample example);
}