package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.RoomDataModule;
import com.chilicool.hdtools.domain.RoomDataModuleExample;
import java.util.List;

import com.chilicool.hdtools.model.DataModuleSimp;
import com.chilicool.hdtools.model.RoomDataSimp;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RoomDataModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int countByExample(RoomDataModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int deleteByExample(RoomDataModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int insert(RoomDataModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int insertSelective(RoomDataModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    List<RoomDataModule> selectByExample(RoomDataModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    RoomDataModule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomDataModule record, @Param("example") RoomDataModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomDataModule record, @Param("example") RoomDataModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomDataModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomDataModule record);

    /**
     * 获取所有房间数据模块
     *
     * @return
     */
    List<DataModuleSimp> getAllDataModuleSimp();

    /**
     * 获取所有房间数据
     *
     * @return
     */
    List<RoomDataSimp> getAllRoomDataSimp();
}