package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.RoomModule;
import com.chilicool.hdtools.domain.RoomModuleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RoomModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module
     *
     * @mbggenerated
     */
    int countByExample(RoomModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module
     *
     * @mbggenerated
     */
    int deleteByExample(RoomModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module
     *
     * @mbggenerated
     */
    int insert(RoomModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module
     *
     * @mbggenerated
     */
    int insertSelective(RoomModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module
     *
     * @mbggenerated
     */
    List<RoomModule> selectByExample(RoomModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomModule record, @Param("example") RoomModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomModule record, @Param("example") RoomModuleExample example);
}