package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.RoomEnumParam;
import com.chilicool.hdtools.domain.RoomEnumParamExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RoomEnumParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_enum_param
     *
     * @mbggenerated
     */
    int countByExample(RoomEnumParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_enum_param
     *
     * @mbggenerated
     */
    int deleteByExample(RoomEnumParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_enum_param
     *
     * @mbggenerated
     */
    int insert(RoomEnumParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_enum_param
     *
     * @mbggenerated
     */
    int insertSelective(RoomEnumParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_enum_param
     *
     * @mbggenerated
     */
    List<RoomEnumParam> selectByExample(RoomEnumParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_enum_param
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomEnumParam record, @Param("example") RoomEnumParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_enum_param
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomEnumParam record, @Param("example") RoomEnumParamExample example);
}