package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.RoomModuleEnum;
import com.chilicool.hdtools.domain.RoomModuleEnumExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RoomModuleEnumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module_enum
     *
     * @mbggenerated
     */
    int countByExample(RoomModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module_enum
     *
     * @mbggenerated
     */
    int deleteByExample(RoomModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module_enum
     *
     * @mbggenerated
     */
    int insert(RoomModuleEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module_enum
     *
     * @mbggenerated
     */
    int insertSelective(RoomModuleEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module_enum
     *
     * @mbggenerated
     */
    List<RoomModuleEnum> selectByExample(RoomModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module_enum
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomModuleEnum record, @Param("example") RoomModuleEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_module_enum
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomModuleEnum record, @Param("example") RoomModuleEnumExample example);
}