package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.RoomDataDetail;
import com.chilicool.hdtools.domain.RoomDataDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RoomDataDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int countByExample(RoomDataDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int deleteByExample(RoomDataDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int insert(RoomDataDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int insertSelective(RoomDataDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    List<RoomDataDetail> selectByExample(RoomDataDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    RoomDataDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomDataDetail record, @Param("example") RoomDataDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomDataDetail record, @Param("example") RoomDataDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomDataDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_data_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomDataDetail record);

    /**
     * 加载房间参数设置
     *
     * @param roomId
     * @return
     */
    List<String> loadCurrRoomDeail(Long roomId);
}