package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.SpecRoomData;
import com.chilicool.hdtools.domain.SpecRoomDataExample;
import java.util.List;

import com.chilicool.hdtools.model.SpecRoomSimple;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SpecRoomDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int countByExample(SpecRoomDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int deleteByExample(SpecRoomDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int insert(SpecRoomData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int insertSelective(SpecRoomData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    List<SpecRoomData> selectByExample(SpecRoomDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    SpecRoomData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SpecRoomData record, @Param("example") SpecRoomDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SpecRoomData record, @Param("example") SpecRoomDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecRoomData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_room_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecRoomData record);

    /**
     * 查询所有样板房间数据
     *
     * @return
     */
    List<SpecRoomSimple> loadAllSpecRoomDetail();

}