package com.chilicool.hdtools.dao;

import com.chilicool.hdtools.domain.VersionInfo;
import com.chilicool.hdtools.domain.VersionInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface VersionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    int countByExample(VersionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    int deleteByExample(VersionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    long insert(VersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    long insertSelective(VersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    List<VersionInfo> selectByExample(VersionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    VersionInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VersionInfo record, @Param("example") VersionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VersionInfo record, @Param("example") VersionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VersionInfo record);
}