package com.chilicool.hdtools.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AreaInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public AreaInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table area_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("PROJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("PROJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Long value) {
            addCriterion("PROJ_ID =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Long value) {
            addCriterion("PROJ_ID <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Long value) {
            addCriterion("PROJ_ID >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Long value) {
            addCriterion("PROJ_ID <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Long> values) {
            addCriterion("PROJ_ID in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Long> values) {
            addCriterion("PROJ_ID not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdIsNull() {
            addCriterion("DEPT_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdIsNotNull() {
            addCriterion("DEPT_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdEqualTo(Long value) {
            addCriterion("DEPT_TYPE_ID =", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdNotEqualTo(Long value) {
            addCriterion("DEPT_TYPE_ID <>", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdGreaterThan(Long value) {
            addCriterion("DEPT_TYPE_ID >", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEPT_TYPE_ID >=", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdLessThan(Long value) {
            addCriterion("DEPT_TYPE_ID <", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("DEPT_TYPE_ID <=", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdIn(List<Long> values) {
            addCriterion("DEPT_TYPE_ID in", values, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdNotIn(List<Long> values) {
            addCriterion("DEPT_TYPE_ID not in", values, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdBetween(Long value1, Long value2) {
            addCriterion("DEPT_TYPE_ID between", value1, value2, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("DEPT_TYPE_ID not between", value1, value2, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Long value) {
            addCriterion("DEPT_ID =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Long value) {
            addCriterion("DEPT_ID <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Long value) {
            addCriterion("DEPT_ID >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEPT_ID >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Long value) {
            addCriterion("DEPT_ID <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Long value) {
            addCriterion("DEPT_ID <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Long> values) {
            addCriterion("DEPT_ID in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Long> values) {
            addCriterion("DEPT_ID not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Long value1, Long value2) {
            addCriterion("DEPT_ID between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Long value1, Long value2) {
            addCriterion("DEPT_ID not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIsNull() {
            addCriterion("OFFICE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIsNotNull() {
            addCriterion("OFFICE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeNameEqualTo(String value) {
            addCriterion("OFFICE_NAME =", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotEqualTo(String value) {
            addCriterion("OFFICE_NAME <>", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameGreaterThan(String value) {
            addCriterion("OFFICE_NAME >", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_NAME >=", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLessThan(String value) {
            addCriterion("OFFICE_NAME <", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_NAME <=", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLike(String value) {
            addCriterion("OFFICE_NAME like", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotLike(String value) {
            addCriterion("OFFICE_NAME not like", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIn(List<String> values) {
            addCriterion("OFFICE_NAME in", values, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotIn(List<String> values) {
            addCriterion("OFFICE_NAME not in", values, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameBetween(String value1, String value2) {
            addCriterion("OFFICE_NAME between", value1, value2, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotBetween(String value1, String value2) {
            addCriterion("OFFICE_NAME not between", value1, value2, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeIsNull() {
            addCriterion("OFFICE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeIsNotNull() {
            addCriterion("OFFICE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeEqualTo(String value) {
            addCriterion("OFFICE_CODE =", value, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeNotEqualTo(String value) {
            addCriterion("OFFICE_CODE <>", value, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeGreaterThan(String value) {
            addCriterion("OFFICE_CODE >", value, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_CODE >=", value, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeLessThan(String value) {
            addCriterion("OFFICE_CODE <", value, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_CODE <=", value, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeLike(String value) {
            addCriterion("OFFICE_CODE like", value, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeNotLike(String value) {
            addCriterion("OFFICE_CODE not like", value, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeIn(List<String> values) {
            addCriterion("OFFICE_CODE in", values, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeNotIn(List<String> values) {
            addCriterion("OFFICE_CODE not in", values, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeBetween(String value1, String value2) {
            addCriterion("OFFICE_CODE between", value1, value2, "officeCode");
            return (Criteria) this;
        }

        public Criteria andOfficeCodeNotBetween(String value1, String value2) {
            addCriterion("OFFICE_CODE not between", value1, value2, "officeCode");
            return (Criteria) this;
        }

        public Criteria andNameSpellingIsNull() {
            addCriterion("NAME_SPELLING is null");
            return (Criteria) this;
        }

        public Criteria andNameSpellingIsNotNull() {
            addCriterion("NAME_SPELLING is not null");
            return (Criteria) this;
        }

        public Criteria andNameSpellingEqualTo(String value) {
            addCriterion("NAME_SPELLING =", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingNotEqualTo(String value) {
            addCriterion("NAME_SPELLING <>", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingGreaterThan(String value) {
            addCriterion("NAME_SPELLING >", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingGreaterThanOrEqualTo(String value) {
            addCriterion("NAME_SPELLING >=", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingLessThan(String value) {
            addCriterion("NAME_SPELLING <", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingLessThanOrEqualTo(String value) {
            addCriterion("NAME_SPELLING <=", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingLike(String value) {
            addCriterion("NAME_SPELLING like", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingNotLike(String value) {
            addCriterion("NAME_SPELLING not like", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingIn(List<String> values) {
            addCriterion("NAME_SPELLING in", values, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingNotIn(List<String> values) {
            addCriterion("NAME_SPELLING not in", values, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingBetween(String value1, String value2) {
            addCriterion("NAME_SPELLING between", value1, value2, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingNotBetween(String value1, String value2) {
            addCriterion("NAME_SPELLING not between", value1, value2, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameCodeIsNull() {
            addCriterion("NAME_CODE is null");
            return (Criteria) this;
        }

        public Criteria andNameCodeIsNotNull() {
            addCriterion("NAME_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andNameCodeEqualTo(String value) {
            addCriterion("NAME_CODE =", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeNotEqualTo(String value) {
            addCriterion("NAME_CODE <>", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeGreaterThan(String value) {
            addCriterion("NAME_CODE >", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeGreaterThanOrEqualTo(String value) {
            addCriterion("NAME_CODE >=", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeLessThan(String value) {
            addCriterion("NAME_CODE <", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeLessThanOrEqualTo(String value) {
            addCriterion("NAME_CODE <=", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeLike(String value) {
            addCriterion("NAME_CODE like", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeNotLike(String value) {
            addCriterion("NAME_CODE not like", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeIn(List<String> values) {
            addCriterion("NAME_CODE in", values, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeNotIn(List<String> values) {
            addCriterion("NAME_CODE not in", values, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeBetween(String value1, String value2) {
            addCriterion("NAME_CODE between", value1, value2, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeNotBetween(String value1, String value2) {
            addCriterion("NAME_CODE not between", value1, value2, "nameCode");
            return (Criteria) this;
        }

        public Criteria andOrderIdxIsNull() {
            addCriterion("ORDER_IDX is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdxIsNotNull() {
            addCriterion("ORDER_IDX is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdxEqualTo(Short value) {
            addCriterion("ORDER_IDX =", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxNotEqualTo(Short value) {
            addCriterion("ORDER_IDX <>", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxGreaterThan(Short value) {
            addCriterion("ORDER_IDX >", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxGreaterThanOrEqualTo(Short value) {
            addCriterion("ORDER_IDX >=", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxLessThan(Short value) {
            addCriterion("ORDER_IDX <", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxLessThanOrEqualTo(Short value) {
            addCriterion("ORDER_IDX <=", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxIn(List<Short> values) {
            addCriterion("ORDER_IDX in", values, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxNotIn(List<Short> values) {
            addCriterion("ORDER_IDX not in", values, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxBetween(Short value1, Short value2) {
            addCriterion("ORDER_IDX between", value1, value2, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxNotBetween(Short value1, Short value2) {
            addCriterion("ORDER_IDX not between", value1, value2, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderNameIsNull() {
            addCriterion("ORDER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrderNameIsNotNull() {
            addCriterion("ORDER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNameEqualTo(String value) {
            addCriterion("ORDER_NAME =", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotEqualTo(String value) {
            addCriterion("ORDER_NAME <>", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameGreaterThan(String value) {
            addCriterion("ORDER_NAME >", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NAME >=", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLessThan(String value) {
            addCriterion("ORDER_NAME <", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NAME <=", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLike(String value) {
            addCriterion("ORDER_NAME like", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotLike(String value) {
            addCriterion("ORDER_NAME not like", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameIn(List<String> values) {
            addCriterion("ORDER_NAME in", values, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotIn(List<String> values) {
            addCriterion("ORDER_NAME not in", values, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameBetween(String value1, String value2) {
            addCriterion("ORDER_NAME between", value1, value2, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotBetween(String value1, String value2) {
            addCriterion("ORDER_NAME not between", value1, value2, "orderName");
            return (Criteria) this;
        }

        public Criteria andCntIsNull() {
            addCriterion("CNT is null");
            return (Criteria) this;
        }

        public Criteria andCntIsNotNull() {
            addCriterion("CNT is not null");
            return (Criteria) this;
        }

        public Criteria andCntEqualTo(Integer value) {
            addCriterion("CNT =", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotEqualTo(Integer value) {
            addCriterion("CNT <>", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntGreaterThan(Integer value) {
            addCriterion("CNT >", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("CNT >=", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntLessThan(Integer value) {
            addCriterion("CNT <", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntLessThanOrEqualTo(Integer value) {
            addCriterion("CNT <=", value, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntIn(List<Integer> values) {
            addCriterion("CNT in", values, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotIn(List<Integer> values) {
            addCriterion("CNT not in", values, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntBetween(Integer value1, Integer value2) {
            addCriterion("CNT between", value1, value2, "cnt");
            return (Criteria) this;
        }

        public Criteria andCntNotBetween(Integer value1, Integer value2) {
            addCriterion("CNT not between", value1, value2, "cnt");
            return (Criteria) this;
        }

        public Criteria andAreaTotalIsNull() {
            addCriterion("AREA_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andAreaTotalIsNotNull() {
            addCriterion("AREA_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andAreaTotalEqualTo(Double value) {
            addCriterion("AREA_TOTAL =", value, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalNotEqualTo(Double value) {
            addCriterion("AREA_TOTAL <>", value, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalGreaterThan(Double value) {
            addCriterion("AREA_TOTAL >", value, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalGreaterThanOrEqualTo(Double value) {
            addCriterion("AREA_TOTAL >=", value, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalLessThan(Double value) {
            addCriterion("AREA_TOTAL <", value, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalLessThanOrEqualTo(Double value) {
            addCriterion("AREA_TOTAL <=", value, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalIn(List<Double> values) {
            addCriterion("AREA_TOTAL in", values, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalNotIn(List<Double> values) {
            addCriterion("AREA_TOTAL not in", values, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalBetween(Double value1, Double value2) {
            addCriterion("AREA_TOTAL between", value1, value2, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaTotalNotBetween(Double value1, Double value2) {
            addCriterion("AREA_TOTAL not between", value1, value2, "areaTotal");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryIsNull() {
            addCriterion("AREA_SUMMARY is null");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryIsNotNull() {
            addCriterion("AREA_SUMMARY is not null");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryEqualTo(Double value) {
            addCriterion("AREA_SUMMARY =", value, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryNotEqualTo(Double value) {
            addCriterion("AREA_SUMMARY <>", value, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryGreaterThan(Double value) {
            addCriterion("AREA_SUMMARY >", value, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryGreaterThanOrEqualTo(Double value) {
            addCriterion("AREA_SUMMARY >=", value, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryLessThan(Double value) {
            addCriterion("AREA_SUMMARY <", value, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryLessThanOrEqualTo(Double value) {
            addCriterion("AREA_SUMMARY <=", value, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryIn(List<Double> values) {
            addCriterion("AREA_SUMMARY in", values, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryNotIn(List<Double> values) {
            addCriterion("AREA_SUMMARY not in", values, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryBetween(Double value1, Double value2) {
            addCriterion("AREA_SUMMARY between", value1, value2, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andAreaSummaryNotBetween(Double value1, Double value2) {
            addCriterion("AREA_SUMMARY not between", value1, value2, "areaSummary");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table area_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table area_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}