package com.chilicool.hdtools.domain;

import java.util.Date;

public class AreaSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.AREA_ID
     *
     * @mbggenerated
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.DEPT_TYPE_CODE
     *
     * @mbggenerated
     */
    private String deptTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.DEPT_TYPE_NAME
     *
     * @mbggenerated
     */
    private String deptTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.DEPT_CODE
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.AREA_TOTAL
     *
     * @mbggenerated
     */
    private Double areaTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.AREA_SUMMARY
     *
     * @mbggenerated
     */
    private Double areaSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.AREA_RATIO
     *
     * @mbggenerated
     */
    private Double areaRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_summary.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.ID
     *
     * @return the value of area_summary.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.ID
     *
     * @param id the value for area_summary.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.AREA_ID
     *
     * @return the value of area_summary.AREA_ID
     *
     * @mbggenerated
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.AREA_ID
     *
     * @param areaId the value for area_summary.AREA_ID
     *
     * @mbggenerated
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.DEPT_TYPE_CODE
     *
     * @return the value of area_summary.DEPT_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getDeptTypeCode() {
        return deptTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.DEPT_TYPE_CODE
     *
     * @param deptTypeCode the value for area_summary.DEPT_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setDeptTypeCode(String deptTypeCode) {
        this.deptTypeCode = deptTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.DEPT_TYPE_NAME
     *
     * @return the value of area_summary.DEPT_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getDeptTypeName() {
        return deptTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.DEPT_TYPE_NAME
     *
     * @param deptTypeName the value for area_summary.DEPT_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setDeptTypeName(String deptTypeName) {
        this.deptTypeName = deptTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.DEPT_CODE
     *
     * @return the value of area_summary.DEPT_CODE
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.DEPT_CODE
     *
     * @param deptCode the value for area_summary.DEPT_CODE
     *
     * @mbggenerated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.DEPT_NAME
     *
     * @return the value of area_summary.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.DEPT_NAME
     *
     * @param deptName the value for area_summary.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.AREA_TOTAL
     *
     * @return the value of area_summary.AREA_TOTAL
     *
     * @mbggenerated
     */
    public Double getAreaTotal() {
        return areaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.AREA_TOTAL
     *
     * @param areaTotal the value for area_summary.AREA_TOTAL
     *
     * @mbggenerated
     */
    public void setAreaTotal(Double areaTotal) {
        this.areaTotal = areaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.AREA_SUMMARY
     *
     * @return the value of area_summary.AREA_SUMMARY
     *
     * @mbggenerated
     */
    public Double getAreaSummary() {
        return areaSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.AREA_SUMMARY
     *
     * @param areaSummary the value for area_summary.AREA_SUMMARY
     *
     * @mbggenerated
     */
    public void setAreaSummary(Double areaSummary) {
        this.areaSummary = areaSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.AREA_RATIO
     *
     * @return the value of area_summary.AREA_RATIO
     *
     * @mbggenerated
     */
    public Double getAreaRatio() {
        return areaRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.AREA_RATIO
     *
     * @param areaRatio the value for area_summary.AREA_RATIO
     *
     * @mbggenerated
     */
    public void setAreaRatio(Double areaRatio) {
        this.areaRatio = areaRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.CREATE_TIME
     *
     * @return the value of area_summary.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.CREATE_TIME
     *
     * @param createTime the value for area_summary.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.UPDATE_TIME
     *
     * @return the value of area_summary.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.UPDATE_TIME
     *
     * @param updateTime the value for area_summary.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_summary.NOTE
     *
     * @return the value of area_summary.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_summary.NOTE
     *
     * @param note the value for area_summary.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}