package com.chilicool.hdtools.domain;

import java.util.Date;

public class DataModuleEnum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.MODULE_ID
     *
     * @mbggenerated
     */
    private Long moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.ENUM_NAME
     *
     * @mbggenerated
     */
    private String enumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.ENUM_CODE
     *
     * @mbggenerated
     */
    private String enumCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.ORDER_IDX
     *
     * @mbggenerated
     */
    private Short orderIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.NAME_SPELLING
     *
     * @mbggenerated
     */
    private String nameSpelling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.NAME_CODE
     *
     * @mbggenerated
     */
    private String nameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.SELECT_TYPE
     *
     * @mbggenerated
     */
    private String selectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.ID
     *
     * @return the value of data_module_enum.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.ID
     *
     * @param id the value for data_module_enum.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.MODULE_ID
     *
     * @return the value of data_module_enum.MODULE_ID
     *
     * @mbggenerated
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.MODULE_ID
     *
     * @param moduleId the value for data_module_enum.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.ENUM_NAME
     *
     * @return the value of data_module_enum.ENUM_NAME
     *
     * @mbggenerated
     */
    public String getEnumName() {
        return enumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.ENUM_NAME
     *
     * @param enumName the value for data_module_enum.ENUM_NAME
     *
     * @mbggenerated
     */
    public void setEnumName(String enumName) {
        this.enumName = enumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.ENUM_CODE
     *
     * @return the value of data_module_enum.ENUM_CODE
     *
     * @mbggenerated
     */
    public String getEnumCode() {
        return enumCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.ENUM_CODE
     *
     * @param enumCode the value for data_module_enum.ENUM_CODE
     *
     * @mbggenerated
     */
    public void setEnumCode(String enumCode) {
        this.enumCode = enumCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.ORDER_IDX
     *
     * @return the value of data_module_enum.ORDER_IDX
     *
     * @mbggenerated
     */
    public Short getOrderIdx() {
        return orderIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.ORDER_IDX
     *
     * @param orderIdx the value for data_module_enum.ORDER_IDX
     *
     * @mbggenerated
     */
    public void setOrderIdx(Short orderIdx) {
        this.orderIdx = orderIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.NAME_SPELLING
     *
     * @return the value of data_module_enum.NAME_SPELLING
     *
     * @mbggenerated
     */
    public String getNameSpelling() {
        return nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.NAME_SPELLING
     *
     * @param nameSpelling the value for data_module_enum.NAME_SPELLING
     *
     * @mbggenerated
     */
    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.NAME_CODE
     *
     * @return the value of data_module_enum.NAME_CODE
     *
     * @mbggenerated
     */
    public String getNameCode() {
        return nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.NAME_CODE
     *
     * @param nameCode the value for data_module_enum.NAME_CODE
     *
     * @mbggenerated
     */
    public void setNameCode(String nameCode) {
        this.nameCode = nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.SELECT_TYPE
     *
     * @return the value of data_module_enum.SELECT_TYPE
     *
     * @mbggenerated
     */
    public String getSelectType() {
        return selectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.SELECT_TYPE
     *
     * @param selectType the value for data_module_enum.SELECT_TYPE
     *
     * @mbggenerated
     */
    public void setSelectType(String selectType) {
        this.selectType = selectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.CREATE_TIME
     *
     * @return the value of data_module_enum.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.CREATE_TIME
     *
     * @param createTime the value for data_module_enum.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum.NOTE
     *
     * @return the value of data_module_enum.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum.NOTE
     *
     * @param note the value for data_module_enum.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}