package com.chilicool.hdtools.domain;

import java.util.Date;

public class DataModuleEnumParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.MODULE_ID
     *
     * @mbggenerated
     */
    private Long moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.ENUM_ID
     *
     * @mbggenerated
     */
    private Long enumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.ENUM_PARAM_NAME
     *
     * @mbggenerated
     */
    private String enumParamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.ENUM_PARAM_CODE
     *
     * @mbggenerated
     */
    private String enumParamCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.ORDER_IDX
     *
     * @mbggenerated
     */
    private Short orderIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.NAME_SPELLING
     *
     * @mbggenerated
     */
    private String nameSpelling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.NAME_CODE
     *
     * @mbggenerated
     */
    private String nameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_module_enum_param.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.ID
     *
     * @return the value of data_module_enum_param.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.ID
     *
     * @param id the value for data_module_enum_param.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.MODULE_ID
     *
     * @return the value of data_module_enum_param.MODULE_ID
     *
     * @mbggenerated
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.MODULE_ID
     *
     * @param moduleId the value for data_module_enum_param.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.ENUM_ID
     *
     * @return the value of data_module_enum_param.ENUM_ID
     *
     * @mbggenerated
     */
    public Long getEnumId() {
        return enumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.ENUM_ID
     *
     * @param enumId the value for data_module_enum_param.ENUM_ID
     *
     * @mbggenerated
     */
    public void setEnumId(Long enumId) {
        this.enumId = enumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.ENUM_PARAM_NAME
     *
     * @return the value of data_module_enum_param.ENUM_PARAM_NAME
     *
     * @mbggenerated
     */
    public String getEnumParamName() {
        return enumParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.ENUM_PARAM_NAME
     *
     * @param enumParamName the value for data_module_enum_param.ENUM_PARAM_NAME
     *
     * @mbggenerated
     */
    public void setEnumParamName(String enumParamName) {
        this.enumParamName = enumParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.ENUM_PARAM_CODE
     *
     * @return the value of data_module_enum_param.ENUM_PARAM_CODE
     *
     * @mbggenerated
     */
    public String getEnumParamCode() {
        return enumParamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.ENUM_PARAM_CODE
     *
     * @param enumParamCode the value for data_module_enum_param.ENUM_PARAM_CODE
     *
     * @mbggenerated
     */
    public void setEnumParamCode(String enumParamCode) {
        this.enumParamCode = enumParamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.ORDER_IDX
     *
     * @return the value of data_module_enum_param.ORDER_IDX
     *
     * @mbggenerated
     */
    public Short getOrderIdx() {
        return orderIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.ORDER_IDX
     *
     * @param orderIdx the value for data_module_enum_param.ORDER_IDX
     *
     * @mbggenerated
     */
    public void setOrderIdx(Short orderIdx) {
        this.orderIdx = orderIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.NAME_SPELLING
     *
     * @return the value of data_module_enum_param.NAME_SPELLING
     *
     * @mbggenerated
     */
    public String getNameSpelling() {
        return nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.NAME_SPELLING
     *
     * @param nameSpelling the value for data_module_enum_param.NAME_SPELLING
     *
     * @mbggenerated
     */
    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.NAME_CODE
     *
     * @return the value of data_module_enum_param.NAME_CODE
     *
     * @mbggenerated
     */
    public String getNameCode() {
        return nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.NAME_CODE
     *
     * @param nameCode the value for data_module_enum_param.NAME_CODE
     *
     * @mbggenerated
     */
    public void setNameCode(String nameCode) {
        this.nameCode = nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.CREATE_TIME
     *
     * @return the value of data_module_enum_param.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.CREATE_TIME
     *
     * @param createTime the value for data_module_enum_param.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_module_enum_param.NOTE
     *
     * @return the value of data_module_enum_param.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_module_enum_param.NOTE
     *
     * @param note the value for data_module_enum_param.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}