package com.chilicool.hdtools.domain;

import java.util.Date;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.PROJ_ID
     *
     * @mbggenerated
     */
    private Long projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DEPT_TYPE_ID
     *
     * @mbggenerated
     */
    private Long deptTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DEPT_CODE
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.NAME_SPELLING
     *
     * @mbggenerated
     */
    private String nameSpelling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.NAME_CODE
     *
     * @mbggenerated
     */
    private String nameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.ORDER_IDX
     *
     * @mbggenerated
     */
    private Short orderIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.ORDER_NAME
     *
     * @mbggenerated
     */
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.PLAN_AREA
     *
     * @mbggenerated
     */
    private Double planArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DESIGN_AREA
     *
     * @mbggenerated
     */
    private Double designArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.PLAN_AREA_PERSENT
     *
     * @mbggenerated
     */
    private Double planAreaPersent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.DESIGN_AREA_PERSENT
     *
     * @mbggenerated
     */
    private Double designAreaPersent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.ID
     *
     * @return the value of department.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.ID
     *
     * @param id the value for department.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.PROJ_ID
     *
     * @return the value of department.PROJ_ID
     *
     * @mbggenerated
     */
    public Long getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.PROJ_ID
     *
     * @param projId the value for department.PROJ_ID
     *
     * @mbggenerated
     */
    public void setProjId(Long projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DEPT_TYPE_ID
     *
     * @return the value of department.DEPT_TYPE_ID
     *
     * @mbggenerated
     */
    public Long getDeptTypeId() {
        return deptTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DEPT_TYPE_ID
     *
     * @param deptTypeId the value for department.DEPT_TYPE_ID
     *
     * @mbggenerated
     */
    public void setDeptTypeId(Long deptTypeId) {
        this.deptTypeId = deptTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DEPT_NAME
     *
     * @return the value of department.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DEPT_NAME
     *
     * @param deptName the value for department.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DEPT_CODE
     *
     * @return the value of department.DEPT_CODE
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DEPT_CODE
     *
     * @param deptCode the value for department.DEPT_CODE
     *
     * @mbggenerated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.NAME_SPELLING
     *
     * @return the value of department.NAME_SPELLING
     *
     * @mbggenerated
     */
    public String getNameSpelling() {
        return nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.NAME_SPELLING
     *
     * @param nameSpelling the value for department.NAME_SPELLING
     *
     * @mbggenerated
     */
    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.NAME_CODE
     *
     * @return the value of department.NAME_CODE
     *
     * @mbggenerated
     */
    public String getNameCode() {
        return nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.NAME_CODE
     *
     * @param nameCode the value for department.NAME_CODE
     *
     * @mbggenerated
     */
    public void setNameCode(String nameCode) {
        this.nameCode = nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.ORDER_IDX
     *
     * @return the value of department.ORDER_IDX
     *
     * @mbggenerated
     */
    public Short getOrderIdx() {
        return orderIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.ORDER_IDX
     *
     * @param orderIdx the value for department.ORDER_IDX
     *
     * @mbggenerated
     */
    public void setOrderIdx(Short orderIdx) {
        this.orderIdx = orderIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.ORDER_NAME
     *
     * @return the value of department.ORDER_NAME
     *
     * @mbggenerated
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.ORDER_NAME
     *
     * @param orderName the value for department.ORDER_NAME
     *
     * @mbggenerated
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.PLAN_AREA
     *
     * @return the value of department.PLAN_AREA
     *
     * @mbggenerated
     */
    public Double getPlanArea() {
        return planArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.PLAN_AREA
     *
     * @param planArea the value for department.PLAN_AREA
     *
     * @mbggenerated
     */
    public void setPlanArea(Double planArea) {
        this.planArea = planArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DESIGN_AREA
     *
     * @return the value of department.DESIGN_AREA
     *
     * @mbggenerated
     */
    public Double getDesignArea() {
        return designArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DESIGN_AREA
     *
     * @param designArea the value for department.DESIGN_AREA
     *
     * @mbggenerated
     */
    public void setDesignArea(Double designArea) {
        this.designArea = designArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.PLAN_AREA_PERSENT
     *
     * @return the value of department.PLAN_AREA_PERSENT
     *
     * @mbggenerated
     */
    public Double getPlanAreaPersent() {
        return planAreaPersent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.PLAN_AREA_PERSENT
     *
     * @param planAreaPersent the value for department.PLAN_AREA_PERSENT
     *
     * @mbggenerated
     */
    public void setPlanAreaPersent(Double planAreaPersent) {
        this.planAreaPersent = planAreaPersent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.DESIGN_AREA_PERSENT
     *
     * @return the value of department.DESIGN_AREA_PERSENT
     *
     * @mbggenerated
     */
    public Double getDesignAreaPersent() {
        return designAreaPersent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.DESIGN_AREA_PERSENT
     *
     * @param designAreaPersent the value for department.DESIGN_AREA_PERSENT
     *
     * @mbggenerated
     */
    public void setDesignAreaPersent(Double designAreaPersent) {
        this.designAreaPersent = designAreaPersent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.CREATE_TIME
     *
     * @return the value of department.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.CREATE_TIME
     *
     * @param createTime the value for department.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.UPDATE_TIME
     *
     * @return the value of department.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.UPDATE_TIME
     *
     * @param updateTime the value for department.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.NOTE
     *
     * @return the value of department.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.NOTE
     *
     * @param note the value for department.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}