package com.chilicool.hdtools.domain;

import java.util.Date;

public class DeptSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.PROJ_ID
     *
     * @mbggenerated
     */
    private Long projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.PLAN_AREA_TOTAL
     *
     * @mbggenerated
     */
    private Double planAreaTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.DESIGN_AREA_TOTAL
     *
     * @mbggenerated
     */
    private Double designAreaTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.PLAN_AREA_PERSENT
     *
     * @mbggenerated
     */
    private Double planAreaPersent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.DESIGN_AREA_PERSENT
     *
     * @mbggenerated
     */
    private Double designAreaPersent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.PLAN_AREA_RATIO
     *
     * @mbggenerated
     */
    private Double planAreaRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.DESIGN_AREA_RATIO
     *
     * @mbggenerated
     */
    private Double designAreaRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.PLAN_AREA_SUMMARY
     *
     * @mbggenerated
     */
    private Double planAreaSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.DESIGN_AREA_SUMMARY
     *
     * @mbggenerated
     */
    private Double designAreaSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_summary.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.ID
     *
     * @return the value of dept_summary.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.ID
     *
     * @param id the value for dept_summary.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.PROJ_ID
     *
     * @return the value of dept_summary.PROJ_ID
     *
     * @mbggenerated
     */
    public Long getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.PROJ_ID
     *
     * @param projId the value for dept_summary.PROJ_ID
     *
     * @mbggenerated
     */
    public void setProjId(Long projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.PLAN_AREA_TOTAL
     *
     * @return the value of dept_summary.PLAN_AREA_TOTAL
     *
     * @mbggenerated
     */
    public Double getPlanAreaTotal() {
        return planAreaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.PLAN_AREA_TOTAL
     *
     * @param planAreaTotal the value for dept_summary.PLAN_AREA_TOTAL
     *
     * @mbggenerated
     */
    public void setPlanAreaTotal(Double planAreaTotal) {
        this.planAreaTotal = planAreaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.DESIGN_AREA_TOTAL
     *
     * @return the value of dept_summary.DESIGN_AREA_TOTAL
     *
     * @mbggenerated
     */
    public Double getDesignAreaTotal() {
        return designAreaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.DESIGN_AREA_TOTAL
     *
     * @param designAreaTotal the value for dept_summary.DESIGN_AREA_TOTAL
     *
     * @mbggenerated
     */
    public void setDesignAreaTotal(Double designAreaTotal) {
        this.designAreaTotal = designAreaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.PLAN_AREA_PERSENT
     *
     * @return the value of dept_summary.PLAN_AREA_PERSENT
     *
     * @mbggenerated
     */
    public Double getPlanAreaPersent() {
        return planAreaPersent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.PLAN_AREA_PERSENT
     *
     * @param planAreaPersent the value for dept_summary.PLAN_AREA_PERSENT
     *
     * @mbggenerated
     */
    public void setPlanAreaPersent(Double planAreaPersent) {
        this.planAreaPersent = planAreaPersent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.DESIGN_AREA_PERSENT
     *
     * @return the value of dept_summary.DESIGN_AREA_PERSENT
     *
     * @mbggenerated
     */
    public Double getDesignAreaPersent() {
        return designAreaPersent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.DESIGN_AREA_PERSENT
     *
     * @param designAreaPersent the value for dept_summary.DESIGN_AREA_PERSENT
     *
     * @mbggenerated
     */
    public void setDesignAreaPersent(Double designAreaPersent) {
        this.designAreaPersent = designAreaPersent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.PLAN_AREA_RATIO
     *
     * @return the value of dept_summary.PLAN_AREA_RATIO
     *
     * @mbggenerated
     */
    public Double getPlanAreaRatio() {
        return planAreaRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.PLAN_AREA_RATIO
     *
     * @param planAreaRatio the value for dept_summary.PLAN_AREA_RATIO
     *
     * @mbggenerated
     */
    public void setPlanAreaRatio(Double planAreaRatio) {
        this.planAreaRatio = planAreaRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.DESIGN_AREA_RATIO
     *
     * @return the value of dept_summary.DESIGN_AREA_RATIO
     *
     * @mbggenerated
     */
    public Double getDesignAreaRatio() {
        return designAreaRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.DESIGN_AREA_RATIO
     *
     * @param designAreaRatio the value for dept_summary.DESIGN_AREA_RATIO
     *
     * @mbggenerated
     */
    public void setDesignAreaRatio(Double designAreaRatio) {
        this.designAreaRatio = designAreaRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.PLAN_AREA_SUMMARY
     *
     * @return the value of dept_summary.PLAN_AREA_SUMMARY
     *
     * @mbggenerated
     */
    public Double getPlanAreaSummary() {
        return planAreaSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.PLAN_AREA_SUMMARY
     *
     * @param planAreaSummary the value for dept_summary.PLAN_AREA_SUMMARY
     *
     * @mbggenerated
     */
    public void setPlanAreaSummary(Double planAreaSummary) {
        this.planAreaSummary = planAreaSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.DESIGN_AREA_SUMMARY
     *
     * @return the value of dept_summary.DESIGN_AREA_SUMMARY
     *
     * @mbggenerated
     */
    public Double getDesignAreaSummary() {
        return designAreaSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.DESIGN_AREA_SUMMARY
     *
     * @param designAreaSummary the value for dept_summary.DESIGN_AREA_SUMMARY
     *
     * @mbggenerated
     */
    public void setDesignAreaSummary(Double designAreaSummary) {
        this.designAreaSummary = designAreaSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.CREATE_TIME
     *
     * @return the value of dept_summary.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.CREATE_TIME
     *
     * @param createTime the value for dept_summary.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.UPDATE_TIME
     *
     * @return the value of dept_summary.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.UPDATE_TIME
     *
     * @param updateTime the value for dept_summary.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_summary.NOTE
     *
     * @return the value of dept_summary.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_summary.NOTE
     *
     * @param note the value for dept_summary.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}