package com.chilicool.hdtools.domain;

public class ParamsView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column params_view.module_id
     *
     * @mbggenerated
     */
    private Long moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column params_view.module_idx
     *
     * @mbggenerated
     */
    private Short moduleIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column params_view.module_name
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column params_view.enum_id
     *
     * @mbggenerated
     */
    private Long enumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column params_view.enum_idx
     *
     * @mbggenerated
     */
    private Short enumIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column params_view.enum_name
     *
     * @mbggenerated
     */
    private String enumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column params_view.sel_type
     *
     * @mbggenerated
     */
    private String selType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column params_view.module_id
     *
     * @return the value of params_view.module_id
     *
     * @mbggenerated
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column params_view.module_id
     *
     * @param moduleId the value for params_view.module_id
     *
     * @mbggenerated
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column params_view.module_idx
     *
     * @return the value of params_view.module_idx
     *
     * @mbggenerated
     */
    public Short getModuleIdx() {
        return moduleIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column params_view.module_idx
     *
     * @param moduleIdx the value for params_view.module_idx
     *
     * @mbggenerated
     */
    public void setModuleIdx(Short moduleIdx) {
        this.moduleIdx = moduleIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column params_view.module_name
     *
     * @return the value of params_view.module_name
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column params_view.module_name
     *
     * @param moduleName the value for params_view.module_name
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column params_view.enum_id
     *
     * @return the value of params_view.enum_id
     *
     * @mbggenerated
     */
    public Long getEnumId() {
        return enumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column params_view.enum_id
     *
     * @param enumId the value for params_view.enum_id
     *
     * @mbggenerated
     */
    public void setEnumId(Long enumId) {
        this.enumId = enumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column params_view.enum_idx
     *
     * @return the value of params_view.enum_idx
     *
     * @mbggenerated
     */
    public Short getEnumIdx() {
        return enumIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column params_view.enum_idx
     *
     * @param enumIdx the value for params_view.enum_idx
     *
     * @mbggenerated
     */
    public void setEnumIdx(Short enumIdx) {
        this.enumIdx = enumIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column params_view.enum_name
     *
     * @return the value of params_view.enum_name
     *
     * @mbggenerated
     */
    public String getEnumName() {
        return enumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column params_view.enum_name
     *
     * @param enumName the value for params_view.enum_name
     *
     * @mbggenerated
     */
    public void setEnumName(String enumName) {
        this.enumName = enumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column params_view.sel_type
     *
     * @return the value of params_view.sel_type
     *
     * @mbggenerated
     */
    public String getSelType() {
        return selType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column params_view.sel_type
     *
     * @param selType the value for params_view.sel_type
     *
     * @mbggenerated
     */
    public void setSelType(String selType) {
        this.selType = selType;
    }
}