package com.chilicool.hdtools.domain;

import java.util.ArrayList;
import java.util.List;

public class ProjVersionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public ProjVersionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjIdIsNull() {
            addCriterion("PROJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("PROJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Long value) {
            addCriterion("PROJ_ID =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Long value) {
            addCriterion("PROJ_ID <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Long value) {
            addCriterion("PROJ_ID >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Long value) {
            addCriterion("PROJ_ID <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Long> values) {
            addCriterion("PROJ_ID in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Long> values) {
            addCriterion("PROJ_ID not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("GROUP_ID is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("GROUP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Long value) {
            addCriterion("GROUP_ID =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Long value) {
            addCriterion("GROUP_ID <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Long value) {
            addCriterion("GROUP_ID >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("GROUP_ID >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Long value) {
            addCriterion("GROUP_ID <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("GROUP_ID <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Long> values) {
            addCriterion("GROUP_ID in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Long> values) {
            addCriterion("GROUP_ID not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Long value1, Long value2) {
            addCriterion("GROUP_ID between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("GROUP_ID not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andVerIdIsNull() {
            addCriterion("VER_ID is null");
            return (Criteria) this;
        }

        public Criteria andVerIdIsNotNull() {
            addCriterion("VER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVerIdEqualTo(Long value) {
            addCriterion("VER_ID =", value, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdNotEqualTo(Long value) {
            addCriterion("VER_ID <>", value, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdGreaterThan(Long value) {
            addCriterion("VER_ID >", value, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("VER_ID >=", value, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdLessThan(Long value) {
            addCriterion("VER_ID <", value, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdLessThanOrEqualTo(Long value) {
            addCriterion("VER_ID <=", value, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdIn(List<Long> values) {
            addCriterion("VER_ID in", values, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdNotIn(List<Long> values) {
            addCriterion("VER_ID not in", values, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdBetween(Long value1, Long value2) {
            addCriterion("VER_ID between", value1, value2, "verId");
            return (Criteria) this;
        }

        public Criteria andVerIdNotBetween(Long value1, Long value2) {
            addCriterion("VER_ID not between", value1, value2, "verId");
            return (Criteria) this;
        }

        public Criteria andVerStatusIsNull() {
            addCriterion("VER_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andVerStatusIsNotNull() {
            addCriterion("VER_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andVerStatusEqualTo(String value) {
            addCriterion("VER_STATUS =", value, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusNotEqualTo(String value) {
            addCriterion("VER_STATUS <>", value, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusGreaterThan(String value) {
            addCriterion("VER_STATUS >", value, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusGreaterThanOrEqualTo(String value) {
            addCriterion("VER_STATUS >=", value, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusLessThan(String value) {
            addCriterion("VER_STATUS <", value, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusLessThanOrEqualTo(String value) {
            addCriterion("VER_STATUS <=", value, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusLike(String value) {
            addCriterion("VER_STATUS like", value, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusNotLike(String value) {
            addCriterion("VER_STATUS not like", value, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusIn(List<String> values) {
            addCriterion("VER_STATUS in", values, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusNotIn(List<String> values) {
            addCriterion("VER_STATUS not in", values, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusBetween(String value1, String value2) {
            addCriterion("VER_STATUS between", value1, value2, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerStatusNotBetween(String value1, String value2) {
            addCriterion("VER_STATUS not between", value1, value2, "verStatus");
            return (Criteria) this;
        }

        public Criteria andVerInfoIsNull() {
            addCriterion("VER_INFO is null");
            return (Criteria) this;
        }

        public Criteria andVerInfoIsNotNull() {
            addCriterion("VER_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andVerInfoEqualTo(String value) {
            addCriterion("VER_INFO =", value, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoNotEqualTo(String value) {
            addCriterion("VER_INFO <>", value, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoGreaterThan(String value) {
            addCriterion("VER_INFO >", value, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoGreaterThanOrEqualTo(String value) {
            addCriterion("VER_INFO >=", value, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoLessThan(String value) {
            addCriterion("VER_INFO <", value, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoLessThanOrEqualTo(String value) {
            addCriterion("VER_INFO <=", value, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoLike(String value) {
            addCriterion("VER_INFO like", value, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoNotLike(String value) {
            addCriterion("VER_INFO not like", value, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoIn(List<String> values) {
            addCriterion("VER_INFO in", values, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoNotIn(List<String> values) {
            addCriterion("VER_INFO not in", values, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoBetween(String value1, String value2) {
            addCriterion("VER_INFO between", value1, value2, "verInfo");
            return (Criteria) this;
        }

        public Criteria andVerInfoNotBetween(String value1, String value2) {
            addCriterion("VER_INFO not between", value1, value2, "verInfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_version
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proj_version
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}