package com.chilicool.hdtools.domain;

public class ProjVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_version.PROJ_ID
     *
     * @mbggenerated
     */
    private Long projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_version.GROUP_ID
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_version.VER_ID
     *
     * @mbggenerated
     */
    private Long verId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_version.VER_STATUS
     *
     * @mbggenerated
     */
    private String verStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_version.VER_INFO
     *
     * @mbggenerated
     */
    private String verInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_version.PROJ_ID
     *
     * @return the value of proj_version.PROJ_ID
     *
     * @mbggenerated
     */
    public Long getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_version.PROJ_ID
     *
     * @param projId the value for proj_version.PROJ_ID
     *
     * @mbggenerated
     */
    public void setProjId(Long projId) {
        this.projId = projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_version.GROUP_ID
     *
     * @return the value of proj_version.GROUP_ID
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_version.GROUP_ID
     *
     * @param groupId the value for proj_version.GROUP_ID
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_version.VER_ID
     *
     * @return the value of proj_version.VER_ID
     *
     * @mbggenerated
     */
    public Long getVerId() {
        return verId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_version.VER_ID
     *
     * @param verId the value for proj_version.VER_ID
     *
     * @mbggenerated
     */
    public void setVerId(Long verId) {
        this.verId = verId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_version.VER_STATUS
     *
     * @return the value of proj_version.VER_STATUS
     *
     * @mbggenerated
     */
    public String getVerStatus() {
        return verStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_version.VER_STATUS
     *
     * @param verStatus the value for proj_version.VER_STATUS
     *
     * @mbggenerated
     */
    public void setVerStatus(String verStatus) {
        this.verStatus = verStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_version.VER_INFO
     *
     * @return the value of proj_version.VER_INFO
     *
     * @mbggenerated
     */
    public String getVerInfo() {
        return verInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_version.VER_INFO
     *
     * @param verInfo the value for proj_version.VER_INFO
     *
     * @mbggenerated
     */
    public void setVerInfo(String verInfo) {
        this.verInfo = verInfo;
    }
}