package com.chilicool.hdtools.domain;

import java.util.Date;

public class RoomDataDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_detail.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_detail.ROOM_ID
     *
     * @mbggenerated
     */
    private Long roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_detail.MODULE_ID
     *
     * @mbggenerated
     */
    private Long moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_detail.ENUM_ID
     *
     * @mbggenerated
     */
    private Long enumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_detail.PARAM_ID
     *
     * @mbggenerated
     */
    private Long paramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_detail.MODULE_ENUM
     *
     * @mbggenerated
     */
    private String moduleEnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_detail.MODULE_PARAM
     *
     * @mbggenerated
     */
    private String moduleParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_detail.ID
     *
     * @return the value of room_data_detail.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_detail.ID
     *
     * @param id the value for room_data_detail.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_detail.ROOM_ID
     *
     * @return the value of room_data_detail.ROOM_ID
     *
     * @mbggenerated
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_detail.ROOM_ID
     *
     * @param roomId the value for room_data_detail.ROOM_ID
     *
     * @mbggenerated
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_detail.MODULE_ID
     *
     * @return the value of room_data_detail.MODULE_ID
     *
     * @mbggenerated
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_detail.MODULE_ID
     *
     * @param moduleId the value for room_data_detail.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_detail.ENUM_ID
     *
     * @return the value of room_data_detail.ENUM_ID
     *
     * @mbggenerated
     */
    public Long getEnumId() {
        return enumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_detail.ENUM_ID
     *
     * @param enumId the value for room_data_detail.ENUM_ID
     *
     * @mbggenerated
     */
    public void setEnumId(Long enumId) {
        this.enumId = enumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_detail.PARAM_ID
     *
     * @return the value of room_data_detail.PARAM_ID
     *
     * @mbggenerated
     */
    public Long getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_detail.PARAM_ID
     *
     * @param paramId the value for room_data_detail.PARAM_ID
     *
     * @mbggenerated
     */
    public void setParamId(Long paramId) {
        this.paramId = paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_detail.MODULE_ENUM
     *
     * @return the value of room_data_detail.MODULE_ENUM
     *
     * @mbggenerated
     */
    public String getModuleEnum() {
        return moduleEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_detail.MODULE_ENUM
     *
     * @param moduleEnum the value for room_data_detail.MODULE_ENUM
     *
     * @mbggenerated
     */
    public void setModuleEnum(String moduleEnum) {
        this.moduleEnum = moduleEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_detail.MODULE_PARAM
     *
     * @return the value of room_data_detail.MODULE_PARAM
     *
     * @mbggenerated
     */
    public String getModuleParam() {
        return moduleParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_detail.MODULE_PARAM
     *
     * @param moduleParam the value for room_data_detail.MODULE_PARAM
     *
     * @mbggenerated
     */
    public void setModuleParam(String moduleParam) {
        this.moduleParam = moduleParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_detail.CREATE_TIME
     *
     * @return the value of room_data_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_detail.CREATE_TIME
     *
     * @param createTime the value for room_data_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}