package com.chilicool.hdtools.domain;

import java.util.Date;

public class RoomDataModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.MODULE_NAME
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.MODULE_TYPE
     *
     * @mbggenerated
     */
    private String moduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.MODULE_CODE
     *
     * @mbggenerated
     */
    private String moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.ORDER_IDX
     *
     * @mbggenerated
     */
    private Short orderIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.NAME_SPELLING
     *
     * @mbggenerated
     */
    private String nameSpelling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.NAME_CODE
     *
     * @mbggenerated
     */
    private String nameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_data_module.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.ID
     *
     * @return the value of room_data_module.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.ID
     *
     * @param id the value for room_data_module.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.MODULE_NAME
     *
     * @return the value of room_data_module.MODULE_NAME
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.MODULE_NAME
     *
     * @param moduleName the value for room_data_module.MODULE_NAME
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.MODULE_TYPE
     *
     * @return the value of room_data_module.MODULE_TYPE
     *
     * @mbggenerated
     */
    public String getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.MODULE_TYPE
     *
     * @param moduleType the value for room_data_module.MODULE_TYPE
     *
     * @mbggenerated
     */
    public void setModuleType(String moduleType) {
        this.moduleType = moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.MODULE_CODE
     *
     * @return the value of room_data_module.MODULE_CODE
     *
     * @mbggenerated
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.MODULE_CODE
     *
     * @param moduleCode the value for room_data_module.MODULE_CODE
     *
     * @mbggenerated
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.ORDER_IDX
     *
     * @return the value of room_data_module.ORDER_IDX
     *
     * @mbggenerated
     */
    public Short getOrderIdx() {
        return orderIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.ORDER_IDX
     *
     * @param orderIdx the value for room_data_module.ORDER_IDX
     *
     * @mbggenerated
     */
    public void setOrderIdx(Short orderIdx) {
        this.orderIdx = orderIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.NAME_SPELLING
     *
     * @return the value of room_data_module.NAME_SPELLING
     *
     * @mbggenerated
     */
    public String getNameSpelling() {
        return nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.NAME_SPELLING
     *
     * @param nameSpelling the value for room_data_module.NAME_SPELLING
     *
     * @mbggenerated
     */
    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.NAME_CODE
     *
     * @return the value of room_data_module.NAME_CODE
     *
     * @mbggenerated
     */
    public String getNameCode() {
        return nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.NAME_CODE
     *
     * @param nameCode the value for room_data_module.NAME_CODE
     *
     * @mbggenerated
     */
    public void setNameCode(String nameCode) {
        this.nameCode = nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.CREATE_TIME
     *
     * @return the value of room_data_module.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.CREATE_TIME
     *
     * @param createTime the value for room_data_module.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_data_module.NOTE
     *
     * @return the value of room_data_module.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_data_module.NOTE
     *
     * @param note the value for room_data_module.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}