package com.chilicool.hdtools.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoomInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public RoomInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNull() {
            addCriterion("PROJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjIdIsNotNull() {
            addCriterion("PROJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjIdEqualTo(Long value) {
            addCriterion("PROJ_ID =", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotEqualTo(Long value) {
            addCriterion("PROJ_ID <>", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThan(Long value) {
            addCriterion("PROJ_ID >", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID >=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThan(Long value) {
            addCriterion("PROJ_ID <", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJ_ID <=", value, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdIn(List<Long> values) {
            addCriterion("PROJ_ID in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotIn(List<Long> values) {
            addCriterion("PROJ_ID not in", values, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andProjIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJ_ID not between", value1, value2, "projId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdIsNull() {
            addCriterion("DEPT_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdIsNotNull() {
            addCriterion("DEPT_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdEqualTo(Long value) {
            addCriterion("DEPT_TYPE_ID =", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdNotEqualTo(Long value) {
            addCriterion("DEPT_TYPE_ID <>", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdGreaterThan(Long value) {
            addCriterion("DEPT_TYPE_ID >", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEPT_TYPE_ID >=", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdLessThan(Long value) {
            addCriterion("DEPT_TYPE_ID <", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("DEPT_TYPE_ID <=", value, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdIn(List<Long> values) {
            addCriterion("DEPT_TYPE_ID in", values, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdNotIn(List<Long> values) {
            addCriterion("DEPT_TYPE_ID not in", values, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdBetween(Long value1, Long value2) {
            addCriterion("DEPT_TYPE_ID between", value1, value2, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("DEPT_TYPE_ID not between", value1, value2, "deptTypeId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Long value) {
            addCriterion("DEPT_ID =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Long value) {
            addCriterion("DEPT_ID <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Long value) {
            addCriterion("DEPT_ID >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEPT_ID >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Long value) {
            addCriterion("DEPT_ID <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Long value) {
            addCriterion("DEPT_ID <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Long> values) {
            addCriterion("DEPT_ID in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Long> values) {
            addCriterion("DEPT_ID not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Long value1, Long value2) {
            addCriterion("DEPT_ID between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Long value1, Long value2) {
            addCriterion("DEPT_ID not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("AREA_ID is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("AREA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Long value) {
            addCriterion("AREA_ID =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Long value) {
            addCriterion("AREA_ID <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Long value) {
            addCriterion("AREA_ID >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AREA_ID >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Long value) {
            addCriterion("AREA_ID <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Long value) {
            addCriterion("AREA_ID <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Long> values) {
            addCriterion("AREA_ID in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Long> values) {
            addCriterion("AREA_ID not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Long value1, Long value2) {
            addCriterion("AREA_ID between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Long value1, Long value2) {
            addCriterion("AREA_ID not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNull() {
            addCriterion("ROOM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNotNull() {
            addCriterion("ROOM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNameEqualTo(String value) {
            addCriterion("ROOM_NAME =", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotEqualTo(String value) {
            addCriterion("ROOM_NAME <>", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThan(String value) {
            addCriterion("ROOM_NAME >", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_NAME >=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThan(String value) {
            addCriterion("ROOM_NAME <", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThanOrEqualTo(String value) {
            addCriterion("ROOM_NAME <=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLike(String value) {
            addCriterion("ROOM_NAME like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotLike(String value) {
            addCriterion("ROOM_NAME not like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameIn(List<String> values) {
            addCriterion("ROOM_NAME in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotIn(List<String> values) {
            addCriterion("ROOM_NAME not in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameBetween(String value1, String value2) {
            addCriterion("ROOM_NAME between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotBetween(String value1, String value2) {
            addCriterion("ROOM_NAME not between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomCodeIsNull() {
            addCriterion("ROOM_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRoomCodeIsNotNull() {
            addCriterion("ROOM_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRoomCodeEqualTo(String value) {
            addCriterion("ROOM_CODE =", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeNotEqualTo(String value) {
            addCriterion("ROOM_CODE <>", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeGreaterThan(String value) {
            addCriterion("ROOM_CODE >", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ROOM_CODE >=", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeLessThan(String value) {
            addCriterion("ROOM_CODE <", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeLessThanOrEqualTo(String value) {
            addCriterion("ROOM_CODE <=", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeLike(String value) {
            addCriterion("ROOM_CODE like", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeNotLike(String value) {
            addCriterion("ROOM_CODE not like", value, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeIn(List<String> values) {
            addCriterion("ROOM_CODE in", values, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeNotIn(List<String> values) {
            addCriterion("ROOM_CODE not in", values, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeBetween(String value1, String value2) {
            addCriterion("ROOM_CODE between", value1, value2, "roomCode");
            return (Criteria) this;
        }

        public Criteria andRoomCodeNotBetween(String value1, String value2) {
            addCriterion("ROOM_CODE not between", value1, value2, "roomCode");
            return (Criteria) this;
        }

        public Criteria andNameSpellingIsNull() {
            addCriterion("NAME_SPELLING is null");
            return (Criteria) this;
        }

        public Criteria andNameSpellingIsNotNull() {
            addCriterion("NAME_SPELLING is not null");
            return (Criteria) this;
        }

        public Criteria andNameSpellingEqualTo(String value) {
            addCriterion("NAME_SPELLING =", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingNotEqualTo(String value) {
            addCriterion("NAME_SPELLING <>", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingGreaterThan(String value) {
            addCriterion("NAME_SPELLING >", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingGreaterThanOrEqualTo(String value) {
            addCriterion("NAME_SPELLING >=", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingLessThan(String value) {
            addCriterion("NAME_SPELLING <", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingLessThanOrEqualTo(String value) {
            addCriterion("NAME_SPELLING <=", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingLike(String value) {
            addCriterion("NAME_SPELLING like", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingNotLike(String value) {
            addCriterion("NAME_SPELLING not like", value, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingIn(List<String> values) {
            addCriterion("NAME_SPELLING in", values, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingNotIn(List<String> values) {
            addCriterion("NAME_SPELLING not in", values, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingBetween(String value1, String value2) {
            addCriterion("NAME_SPELLING between", value1, value2, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameSpellingNotBetween(String value1, String value2) {
            addCriterion("NAME_SPELLING not between", value1, value2, "nameSpelling");
            return (Criteria) this;
        }

        public Criteria andNameCodeIsNull() {
            addCriterion("NAME_CODE is null");
            return (Criteria) this;
        }

        public Criteria andNameCodeIsNotNull() {
            addCriterion("NAME_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andNameCodeEqualTo(String value) {
            addCriterion("NAME_CODE =", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeNotEqualTo(String value) {
            addCriterion("NAME_CODE <>", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeGreaterThan(String value) {
            addCriterion("NAME_CODE >", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeGreaterThanOrEqualTo(String value) {
            addCriterion("NAME_CODE >=", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeLessThan(String value) {
            addCriterion("NAME_CODE <", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeLessThanOrEqualTo(String value) {
            addCriterion("NAME_CODE <=", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeLike(String value) {
            addCriterion("NAME_CODE like", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeNotLike(String value) {
            addCriterion("NAME_CODE not like", value, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeIn(List<String> values) {
            addCriterion("NAME_CODE in", values, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeNotIn(List<String> values) {
            addCriterion("NAME_CODE not in", values, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeBetween(String value1, String value2) {
            addCriterion("NAME_CODE between", value1, value2, "nameCode");
            return (Criteria) this;
        }

        public Criteria andNameCodeNotBetween(String value1, String value2) {
            addCriterion("NAME_CODE not between", value1, value2, "nameCode");
            return (Criteria) this;
        }

        public Criteria andOrderIdxIsNull() {
            addCriterion("ORDER_IDX is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdxIsNotNull() {
            addCriterion("ORDER_IDX is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdxEqualTo(Short value) {
            addCriterion("ORDER_IDX =", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxNotEqualTo(Short value) {
            addCriterion("ORDER_IDX <>", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxGreaterThan(Short value) {
            addCriterion("ORDER_IDX >", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxGreaterThanOrEqualTo(Short value) {
            addCriterion("ORDER_IDX >=", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxLessThan(Short value) {
            addCriterion("ORDER_IDX <", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxLessThanOrEqualTo(Short value) {
            addCriterion("ORDER_IDX <=", value, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxIn(List<Short> values) {
            addCriterion("ORDER_IDX in", values, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxNotIn(List<Short> values) {
            addCriterion("ORDER_IDX not in", values, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxBetween(Short value1, Short value2) {
            addCriterion("ORDER_IDX between", value1, value2, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderIdxNotBetween(Short value1, Short value2) {
            addCriterion("ORDER_IDX not between", value1, value2, "orderIdx");
            return (Criteria) this;
        }

        public Criteria andOrderNameIsNull() {
            addCriterion("ORDER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrderNameIsNotNull() {
            addCriterion("ORDER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNameEqualTo(String value) {
            addCriterion("ORDER_NAME =", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotEqualTo(String value) {
            addCriterion("ORDER_NAME <>", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameGreaterThan(String value) {
            addCriterion("ORDER_NAME >", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NAME >=", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLessThan(String value) {
            addCriterion("ORDER_NAME <", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NAME <=", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameLike(String value) {
            addCriterion("ORDER_NAME like", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotLike(String value) {
            addCriterion("ORDER_NAME not like", value, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameIn(List<String> values) {
            addCriterion("ORDER_NAME in", values, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotIn(List<String> values) {
            addCriterion("ORDER_NAME not in", values, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameBetween(String value1, String value2) {
            addCriterion("ORDER_NAME between", value1, value2, "orderName");
            return (Criteria) this;
        }

        public Criteria andOrderNameNotBetween(String value1, String value2) {
            addCriterion("ORDER_NAME not between", value1, value2, "orderName");
            return (Criteria) this;
        }

        public Criteria andPlanCntIsNull() {
            addCriterion("PLAN_CNT is null");
            return (Criteria) this;
        }

        public Criteria andPlanCntIsNotNull() {
            addCriterion("PLAN_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andPlanCntEqualTo(Integer value) {
            addCriterion("PLAN_CNT =", value, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntNotEqualTo(Integer value) {
            addCriterion("PLAN_CNT <>", value, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntGreaterThan(Integer value) {
            addCriterion("PLAN_CNT >", value, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("PLAN_CNT >=", value, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntLessThan(Integer value) {
            addCriterion("PLAN_CNT <", value, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntLessThanOrEqualTo(Integer value) {
            addCriterion("PLAN_CNT <=", value, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntIn(List<Integer> values) {
            addCriterion("PLAN_CNT in", values, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntNotIn(List<Integer> values) {
            addCriterion("PLAN_CNT not in", values, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntBetween(Integer value1, Integer value2) {
            addCriterion("PLAN_CNT between", value1, value2, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanCntNotBetween(Integer value1, Integer value2) {
            addCriterion("PLAN_CNT not between", value1, value2, "planCnt");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalIsNull() {
            addCriterion("PLAN_AREA_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalIsNotNull() {
            addCriterion("PLAN_AREA_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalEqualTo(Double value) {
            addCriterion("PLAN_AREA_TOTAL =", value, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalNotEqualTo(Double value) {
            addCriterion("PLAN_AREA_TOTAL <>", value, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalGreaterThan(Double value) {
            addCriterion("PLAN_AREA_TOTAL >", value, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalGreaterThanOrEqualTo(Double value) {
            addCriterion("PLAN_AREA_TOTAL >=", value, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalLessThan(Double value) {
            addCriterion("PLAN_AREA_TOTAL <", value, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalLessThanOrEqualTo(Double value) {
            addCriterion("PLAN_AREA_TOTAL <=", value, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalIn(List<Double> values) {
            addCriterion("PLAN_AREA_TOTAL in", values, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalNotIn(List<Double> values) {
            addCriterion("PLAN_AREA_TOTAL not in", values, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalBetween(Double value1, Double value2) {
            addCriterion("PLAN_AREA_TOTAL between", value1, value2, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaTotalNotBetween(Double value1, Double value2) {
            addCriterion("PLAN_AREA_TOTAL not between", value1, value2, "planAreaTotal");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryIsNull() {
            addCriterion("PLAN_AREA_SUMMARY is null");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryIsNotNull() {
            addCriterion("PLAN_AREA_SUMMARY is not null");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryEqualTo(Double value) {
            addCriterion("PLAN_AREA_SUMMARY =", value, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryNotEqualTo(Double value) {
            addCriterion("PLAN_AREA_SUMMARY <>", value, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryGreaterThan(Double value) {
            addCriterion("PLAN_AREA_SUMMARY >", value, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryGreaterThanOrEqualTo(Double value) {
            addCriterion("PLAN_AREA_SUMMARY >=", value, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryLessThan(Double value) {
            addCriterion("PLAN_AREA_SUMMARY <", value, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryLessThanOrEqualTo(Double value) {
            addCriterion("PLAN_AREA_SUMMARY <=", value, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryIn(List<Double> values) {
            addCriterion("PLAN_AREA_SUMMARY in", values, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryNotIn(List<Double> values) {
            addCriterion("PLAN_AREA_SUMMARY not in", values, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryBetween(Double value1, Double value2) {
            addCriterion("PLAN_AREA_SUMMARY between", value1, value2, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andPlanAreaSummaryNotBetween(Double value1, Double value2) {
            addCriterion("PLAN_AREA_SUMMARY not between", value1, value2, "planAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignCntIsNull() {
            addCriterion("DESIGN_CNT is null");
            return (Criteria) this;
        }

        public Criteria andDesignCntIsNotNull() {
            addCriterion("DESIGN_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andDesignCntEqualTo(Integer value) {
            addCriterion("DESIGN_CNT =", value, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntNotEqualTo(Integer value) {
            addCriterion("DESIGN_CNT <>", value, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntGreaterThan(Integer value) {
            addCriterion("DESIGN_CNT >", value, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("DESIGN_CNT >=", value, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntLessThan(Integer value) {
            addCriterion("DESIGN_CNT <", value, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntLessThanOrEqualTo(Integer value) {
            addCriterion("DESIGN_CNT <=", value, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntIn(List<Integer> values) {
            addCriterion("DESIGN_CNT in", values, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntNotIn(List<Integer> values) {
            addCriterion("DESIGN_CNT not in", values, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntBetween(Integer value1, Integer value2) {
            addCriterion("DESIGN_CNT between", value1, value2, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignCntNotBetween(Integer value1, Integer value2) {
            addCriterion("DESIGN_CNT not between", value1, value2, "designCnt");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalIsNull() {
            addCriterion("DESIGN_AREA_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalIsNotNull() {
            addCriterion("DESIGN_AREA_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalEqualTo(Double value) {
            addCriterion("DESIGN_AREA_TOTAL =", value, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalNotEqualTo(Double value) {
            addCriterion("DESIGN_AREA_TOTAL <>", value, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalGreaterThan(Double value) {
            addCriterion("DESIGN_AREA_TOTAL >", value, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalGreaterThanOrEqualTo(Double value) {
            addCriterion("DESIGN_AREA_TOTAL >=", value, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalLessThan(Double value) {
            addCriterion("DESIGN_AREA_TOTAL <", value, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalLessThanOrEqualTo(Double value) {
            addCriterion("DESIGN_AREA_TOTAL <=", value, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalIn(List<Double> values) {
            addCriterion("DESIGN_AREA_TOTAL in", values, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalNotIn(List<Double> values) {
            addCriterion("DESIGN_AREA_TOTAL not in", values, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalBetween(Double value1, Double value2) {
            addCriterion("DESIGN_AREA_TOTAL between", value1, value2, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaTotalNotBetween(Double value1, Double value2) {
            addCriterion("DESIGN_AREA_TOTAL not between", value1, value2, "designAreaTotal");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryIsNull() {
            addCriterion("DESIGN_AREA_SUMMARY is null");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryIsNotNull() {
            addCriterion("DESIGN_AREA_SUMMARY is not null");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryEqualTo(Double value) {
            addCriterion("DESIGN_AREA_SUMMARY =", value, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryNotEqualTo(Double value) {
            addCriterion("DESIGN_AREA_SUMMARY <>", value, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryGreaterThan(Double value) {
            addCriterion("DESIGN_AREA_SUMMARY >", value, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryGreaterThanOrEqualTo(Double value) {
            addCriterion("DESIGN_AREA_SUMMARY >=", value, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryLessThan(Double value) {
            addCriterion("DESIGN_AREA_SUMMARY <", value, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryLessThanOrEqualTo(Double value) {
            addCriterion("DESIGN_AREA_SUMMARY <=", value, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryIn(List<Double> values) {
            addCriterion("DESIGN_AREA_SUMMARY in", values, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryNotIn(List<Double> values) {
            addCriterion("DESIGN_AREA_SUMMARY not in", values, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryBetween(Double value1, Double value2) {
            addCriterion("DESIGN_AREA_SUMMARY between", value1, value2, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andDesignAreaSummaryNotBetween(Double value1, Double value2) {
            addCriterion("DESIGN_AREA_SUMMARY not between", value1, value2, "designAreaSummary");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}