package com.chilicool.hdtools.domain;

import java.util.Date;

public class RoomModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_module.ROOM_ID
     *
     * @mbggenerated
     */
    private Long roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_module.MODULE_ID
     *
     * @mbggenerated
     */
    private Long moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_module.MODULE_NAME
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_module.MODULE_TYPE
     *
     * @mbggenerated
     */
    private String moduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_module.MODULE_CODE
     *
     * @mbggenerated
     */
    private String moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_module.NAME_SPELLING
     *
     * @mbggenerated
     */
    private String nameSpelling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_module.NAME_CODE
     *
     * @mbggenerated
     */
    private String nameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_module.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_module.ROOM_ID
     *
     * @return the value of room_module.ROOM_ID
     *
     * @mbggenerated
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_module.ROOM_ID
     *
     * @param roomId the value for room_module.ROOM_ID
     *
     * @mbggenerated
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_module.MODULE_ID
     *
     * @return the value of room_module.MODULE_ID
     *
     * @mbggenerated
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_module.MODULE_ID
     *
     * @param moduleId the value for room_module.MODULE_ID
     *
     * @mbggenerated
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_module.MODULE_NAME
     *
     * @return the value of room_module.MODULE_NAME
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_module.MODULE_NAME
     *
     * @param moduleName the value for room_module.MODULE_NAME
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_module.MODULE_TYPE
     *
     * @return the value of room_module.MODULE_TYPE
     *
     * @mbggenerated
     */
    public String getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_module.MODULE_TYPE
     *
     * @param moduleType the value for room_module.MODULE_TYPE
     *
     * @mbggenerated
     */
    public void setModuleType(String moduleType) {
        this.moduleType = moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_module.MODULE_CODE
     *
     * @return the value of room_module.MODULE_CODE
     *
     * @mbggenerated
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_module.MODULE_CODE
     *
     * @param moduleCode the value for room_module.MODULE_CODE
     *
     * @mbggenerated
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_module.NAME_SPELLING
     *
     * @return the value of room_module.NAME_SPELLING
     *
     * @mbggenerated
     */
    public String getNameSpelling() {
        return nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_module.NAME_SPELLING
     *
     * @param nameSpelling the value for room_module.NAME_SPELLING
     *
     * @mbggenerated
     */
    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_module.NAME_CODE
     *
     * @return the value of room_module.NAME_CODE
     *
     * @mbggenerated
     */
    public String getNameCode() {
        return nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_module.NAME_CODE
     *
     * @param nameCode the value for room_module.NAME_CODE
     *
     * @mbggenerated
     */
    public void setNameCode(String nameCode) {
        this.nameCode = nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_module.CREATE_TIME
     *
     * @return the value of room_module.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_module.CREATE_TIME
     *
     * @param createTime the value for room_module.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}