package com.chilicool.hdtools.domain;

public class SmSysDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_sys_dict.TYPE_CODE
     *
     * @mbggenerated
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_sys_dict.PARAM_CODE
     *
     * @mbggenerated
     */
    private String paramCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_sys_dict.PARAM_DESC
     *
     * @mbggenerated
     */
    private String paramDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_sys_dict.PARENT_TYPE_CODE
     *
     * @mbggenerated
     */
    private String parentTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_sys_dict.PARENT_PARAM_CODE
     *
     * @mbggenerated
     */
    private String parentParamCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_sys_dict.LANGUAGE_TYPE
     *
     * @mbggenerated
     */
    private String languageType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_sys_dict.TYPE_CODE
     *
     * @return the value of sm_sys_dict.TYPE_CODE
     *
     * @mbggenerated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_sys_dict.TYPE_CODE
     *
     * @param typeCode the value for sm_sys_dict.TYPE_CODE
     *
     * @mbggenerated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_sys_dict.PARAM_CODE
     *
     * @return the value of sm_sys_dict.PARAM_CODE
     *
     * @mbggenerated
     */
    public String getParamCode() {
        return paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_sys_dict.PARAM_CODE
     *
     * @param paramCode the value for sm_sys_dict.PARAM_CODE
     *
     * @mbggenerated
     */
    public void setParamCode(String paramCode) {
        this.paramCode = paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_sys_dict.PARAM_DESC
     *
     * @return the value of sm_sys_dict.PARAM_DESC
     *
     * @mbggenerated
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_sys_dict.PARAM_DESC
     *
     * @param paramDesc the value for sm_sys_dict.PARAM_DESC
     *
     * @mbggenerated
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_sys_dict.PARENT_TYPE_CODE
     *
     * @return the value of sm_sys_dict.PARENT_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getParentTypeCode() {
        return parentTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_sys_dict.PARENT_TYPE_CODE
     *
     * @param parentTypeCode the value for sm_sys_dict.PARENT_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setParentTypeCode(String parentTypeCode) {
        this.parentTypeCode = parentTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_sys_dict.PARENT_PARAM_CODE
     *
     * @return the value of sm_sys_dict.PARENT_PARAM_CODE
     *
     * @mbggenerated
     */
    public String getParentParamCode() {
        return parentParamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_sys_dict.PARENT_PARAM_CODE
     *
     * @param parentParamCode the value for sm_sys_dict.PARENT_PARAM_CODE
     *
     * @mbggenerated
     */
    public void setParentParamCode(String parentParamCode) {
        this.parentParamCode = parentParamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_sys_dict.LANGUAGE_TYPE
     *
     * @return the value of sm_sys_dict.LANGUAGE_TYPE
     *
     * @mbggenerated
     */
    public String getLanguageType() {
        return languageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_sys_dict.LANGUAGE_TYPE
     *
     * @param languageType the value for sm_sys_dict.LANGUAGE_TYPE
     *
     * @mbggenerated
     */
    public void setLanguageType(String languageType) {
        this.languageType = languageType;
    }
}