package com.chilicool.hdtools.domain;

import java.util.Date;

public class SpecRoomData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.SPEC_ROOM_NAME
     *
     * @mbggenerated
     */
    private String specRoomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.DEPT_TYPE_CODE
     *
     * @mbggenerated
     */
    private String deptTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.DEPT_TYPE_NAME
     *
     * @mbggenerated
     */
    private String deptTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.DEPT_ID
     *
     * @mbggenerated
     */
    private Long deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.NAME_SPELLING
     *
     * @mbggenerated
     */
    private String nameSpelling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.NAME_CODE
     *
     * @mbggenerated
     */
    private String nameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spec_room_data.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.ID
     *
     * @return the value of spec_room_data.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.ID
     *
     * @param id the value for spec_room_data.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.SPEC_ROOM_NAME
     *
     * @return the value of spec_room_data.SPEC_ROOM_NAME
     *
     * @mbggenerated
     */
    public String getSpecRoomName() {
        return specRoomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.SPEC_ROOM_NAME
     *
     * @param specRoomName the value for spec_room_data.SPEC_ROOM_NAME
     *
     * @mbggenerated
     */
    public void setSpecRoomName(String specRoomName) {
        this.specRoomName = specRoomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.DEPT_TYPE_CODE
     *
     * @return the value of spec_room_data.DEPT_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getDeptTypeCode() {
        return deptTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.DEPT_TYPE_CODE
     *
     * @param deptTypeCode the value for spec_room_data.DEPT_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setDeptTypeCode(String deptTypeCode) {
        this.deptTypeCode = deptTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.DEPT_TYPE_NAME
     *
     * @return the value of spec_room_data.DEPT_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getDeptTypeName() {
        return deptTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.DEPT_TYPE_NAME
     *
     * @param deptTypeName the value for spec_room_data.DEPT_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setDeptTypeName(String deptTypeName) {
        this.deptTypeName = deptTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.DEPT_ID
     *
     * @return the value of spec_room_data.DEPT_ID
     *
     * @mbggenerated
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.DEPT_ID
     *
     * @param deptId the value for spec_room_data.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.DEPT_NAME
     *
     * @return the value of spec_room_data.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.DEPT_NAME
     *
     * @param deptName the value for spec_room_data.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.NAME_SPELLING
     *
     * @return the value of spec_room_data.NAME_SPELLING
     *
     * @mbggenerated
     */
    public String getNameSpelling() {
        return nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.NAME_SPELLING
     *
     * @param nameSpelling the value for spec_room_data.NAME_SPELLING
     *
     * @mbggenerated
     */
    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.NAME_CODE
     *
     * @return the value of spec_room_data.NAME_CODE
     *
     * @mbggenerated
     */
    public String getNameCode() {
        return nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.NAME_CODE
     *
     * @param nameCode the value for spec_room_data.NAME_CODE
     *
     * @mbggenerated
     */
    public void setNameCode(String nameCode) {
        this.nameCode = nameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.CREATE_TIME
     *
     * @return the value of spec_room_data.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.CREATE_TIME
     *
     * @param createTime the value for spec_room_data.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.UPDATE_TIME
     *
     * @return the value of spec_room_data.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.UPDATE_TIME
     *
     * @param updateTime the value for spec_room_data.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spec_room_data.NOTE
     *
     * @return the value of spec_room_data.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spec_room_data.NOTE
     *
     * @param note the value for spec_room_data.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}