package com.chilicool.hdtools.domain;

import java.util.Date;

public class VersionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.VER_NAME
     *
     * @mbggenerated
     */
    private String verName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.VER_CODE
     *
     * @mbggenerated
     */
    private String verCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.MAJOR
     *
     * @mbggenerated
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.SLAVE
     *
     * @mbggenerated
     */
    private String slave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.EXT
     *
     * @mbggenerated
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.VER_INFO
     *
     * @mbggenerated
     */
    private String verInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.VER_STATUS
     *
     * @mbggenerated
     */
    private String verStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.VER_TYPE
     *
     * @mbggenerated
     */
    private String verType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.OPER_CODE
     *
     * @mbggenerated
     */
    private String operCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_info.NOE
     *
     * @mbggenerated
     */
    private String noe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.ID
     *
     * @return the value of version_info.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.ID
     *
     * @param id the value for version_info.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.VER_NAME
     *
     * @return the value of version_info.VER_NAME
     *
     * @mbggenerated
     */
    public String getVerName() {
        return verName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.VER_NAME
     *
     * @param verName the value for version_info.VER_NAME
     *
     * @mbggenerated
     */
    public void setVerName(String verName) {
        this.verName = verName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.VER_CODE
     *
     * @return the value of version_info.VER_CODE
     *
     * @mbggenerated
     */
    public String getVerCode() {
        return verCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.VER_CODE
     *
     * @param verCode the value for version_info.VER_CODE
     *
     * @mbggenerated
     */
    public void setVerCode(String verCode) {
        this.verCode = verCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.MAJOR
     *
     * @return the value of version_info.MAJOR
     *
     * @mbggenerated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.MAJOR
     *
     * @param major the value for version_info.MAJOR
     *
     * @mbggenerated
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.SLAVE
     *
     * @return the value of version_info.SLAVE
     *
     * @mbggenerated
     */
    public String getSlave() {
        return slave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.SLAVE
     *
     * @param slave the value for version_info.SLAVE
     *
     * @mbggenerated
     */
    public void setSlave(String slave) {
        this.slave = slave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.EXT
     *
     * @return the value of version_info.EXT
     *
     * @mbggenerated
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.EXT
     *
     * @param ext the value for version_info.EXT
     *
     * @mbggenerated
     */
    public void setExt(String ext) {
        this.ext = ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.VER_INFO
     *
     * @return the value of version_info.VER_INFO
     *
     * @mbggenerated
     */
    public String getVerInfo() {
        return verInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.VER_INFO
     *
     * @param verInfo the value for version_info.VER_INFO
     *
     * @mbggenerated
     */
    public void setVerInfo(String verInfo) {
        this.verInfo = verInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.VER_STATUS
     *
     * @return the value of version_info.VER_STATUS
     *
     * @mbggenerated
     */
    public String getVerStatus() {
        return verStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.VER_STATUS
     *
     * @param verStatus the value for version_info.VER_STATUS
     *
     * @mbggenerated
     */
    public void setVerStatus(String verStatus) {
        this.verStatus = verStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.VER_TYPE
     *
     * @return the value of version_info.VER_TYPE
     *
     * @mbggenerated
     */
    public String getVerType() {
        return verType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.VER_TYPE
     *
     * @param verType the value for version_info.VER_TYPE
     *
     * @mbggenerated
     */
    public void setVerType(String verType) {
        this.verType = verType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.CREATE_TIME
     *
     * @return the value of version_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.CREATE_TIME
     *
     * @param createTime the value for version_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.OPER_CODE
     *
     * @return the value of version_info.OPER_CODE
     *
     * @mbggenerated
     */
    public String getOperCode() {
        return operCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.OPER_CODE
     *
     * @param operCode the value for version_info.OPER_CODE
     *
     * @mbggenerated
     */
    public void setOperCode(String operCode) {
        this.operCode = operCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_info.NOE
     *
     * @return the value of version_info.NOE
     *
     * @mbggenerated
     */
    public String getNoe() {
        return noe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_info.NOE
     *
     * @param noe the value for version_info.NOE
     *
     * @mbggenerated
     */
    public void setNoe(String noe) {
        this.noe = noe;
    }
}